"use strict";

module.exports = {
  configs: {
    defineLayerStructureOptions: require("./configs/layer-structure").defineLayerStructureOptions,
  },
  rules: {
    "async-safety": require("./rules/async-safety"),
    "barrel-boundary": require("./rules/barrel-boundary"),
    "comment-contract": require("./rules/comment-contract"),
    "dangerous-api": require("./rules/dangerous-api"),
    "dependency-injection-enforcement": require("./rules/dependency-injection-enforcement"),
    "duplicate-role-detection": require("./rules/duplicate-role-detection"),
    "directory-export-name": require("./rules/directory-export-name"),
    "dto-export-name": require("./rules/dto-export-name"),
    "explicit-public-surface": require("./rules/explicit-public-surface"),
    "forbidden-relative-depth": require("./rules/forbidden-relative-depth"),
    "framework-leakage": require("./rules/framework-leakage"),
    "hooks-export-name": require("./rules/hooks-export-name"),
    "layer-import-direction": require("./rules/layer-import-direction"),
    "layer-structure": require("./rules/layer-structure"),
    "mutation-guard": require("./rules/mutation-guard"),
    "naming-consistency-between-file-and-symbol": require("./rules/naming-consistency-between-file-and-symbol"),
    "name-responsibility-match": require("./rules/name-responsibility-match"),
    "no-cross-layer-instantiation": require("./rules/no-cross-layer-instantiation"),
    "no-empty-catch-or-swallow": require("./rules/no-empty-catch-or-swallow"),
    "no-inline-implementation-in-interface-layer": require("./rules/no-inline-implementation-in-interface-layer"),
    "no-todo-shipping": require("./rules/no-todo-shipping"),
    "presentation-export-name": require("./rules/presentation-export-name"),
    "query-command-separation": require("./rules/query-command-separation"),
    "result-error-handling": require("./rules/result-error-handling"),
    "serialization-boundary": require("./rules/serialization-boundary"),
    "side-effect-boundary": require("./rules/side-effect-boundary"),
    "structured-log-contract": require("./rules/structured-log-contract"),
    "test-coupling-guard": require("./rules/test-coupling-guard"),
    "testability-guard": require("./rules/testability-guard"),
    "usecase-export-name": require("./rules/usecase-export-name"),
  },
};
